#
#	T3D-specific Makefile for FMRI software
#
#	Copyright (c) 1996 Pittsburgh Supercomputing Center
#	Written by Greg Hood, PSC, Sept. 1996
#

CC     = /mpp/bin/cc
LD     = /mpp/bin/mppldr
ARCH_CFLAGS = -T cray-t3d -DRELIABLE -I$(FMRI)/include/$(ARCH) -O
ARCH_LFLAGS =
ARCH_LIBS =
AR     = ar
ARCH_ARFLAGS= -r
RANLIB = echo ranlib not needed on $(ARCH) for
NEWER = $(FMRI)/src/fiat_scripts/test_newer.csh
SHR_EXT = so
SHR_LD = cc -shared

