#
# LINUX-specific Makefile for FMRI software
#
#

CC     = cc
ARCH_CFLAGS = -D_BSD_SOURCE -D_XOPEN_SOURCE=500 \
	-DFORTRAN_ADD_UNDERSCORE -I$(FMRI)/include/$(ARCH) \
	-Wimplicit -g -O3
LD     = cc
ARCH_LFLAGS = 
ARCH_LIBS   = 
AR     = ar
ARCH_ARFLAGS= -r
RANLIB = ranlib 
NEWER = $(FMRI)/src/fiat_scripts/test_newer.csh
SHR_EXT = so
SHR_LD = cc -flat_namespace -bundle -undefined suppress


include Makefile.common
