#
#	T3E-specific Makefile for FMRI software
#
#	Copyright (c) 1996 Pittsburgh Supercomputing Center
#	Written by Greg Hood, PSC, Oct. 1996
#

CC     = cc
ARCH_CFLAGS = -DRELIABLE -DT3D I$(FMRI)/include/$(ARCH) -O3
LD     = cld
ARCH_LFLAGS = -Xm -Dstreams=on
ARCH_LIBS   = -lc -lm -lu -lf -lsci -lfi -lsma -lcomm
AR     = ar
ARCH_ARFLAGS= -r
RANLIB = ranlib
NEWER = $(FMRI)/src/fiat_scripts/test_newer.csh
SHR_EXT = so
SHR_LD = cc -shared

include Makefile.common
