/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.20
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#include "Python.h"

/*************************************************************** -*- c -*-
 * python/precommon.swg
 *
 * Rename all exported symbols from common.swg, to avoid symbol
 * clashes if multiple interpreters are included
 *
 ************************************************************************/

#define SWIG_TypeRegister    SWIG_Python_TypeRegister
#define SWIG_TypeCheck       SWIG_Python_TypeCheck
#define SWIG_TypeCast        SWIG_Python_TypeCast
#define SWIG_TypeDynamicCast SWIG_Python_TypeDynamicCast
#define SWIG_TypeName        SWIG_Python_TypeName
#define SWIG_TypeQuery       SWIG_Python_TypeQuery
#define SWIG_TypeClientData  SWIG_Python_TypeClientData
#define SWIG_PackData        SWIG_Python_PackData 
#define SWIG_UnpackData      SWIG_Python_UnpackData 


/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if defined(_MSC_VER) || defined(__GNUC__)
#    if defined(STATIC_LINKED)
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) extern a
#    else
#      define SWIGEXPORT(a) __declspec(dllexport) a
#      define SWIGIMPORT(a) extern a
#    endif
#  else
#    if defined(__BORLANDC__)
#      define SWIGEXPORT(a) a _export
#      define SWIGIMPORT(a) a _export
#    else
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) a
#    endif
#  endif
#else
#  define SWIGEXPORT(a) a
#  define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#  define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#  define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);
SWIGIMPORT(char *)           SWIG_PackData(char *, void *, int);
SWIGIMPORT(char *)           SWIG_UnpackData(char *, void *, int);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

#endif

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Python_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Python_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Python_MustGetPtr(p, type, argnum, flags)

/* Python-specific SWIG API */
#define SWIG_newvarlink() \
  SWIG_Python_newvarlink()
#define SWIG_addvarlink(p, name, get_attr, set_attr) \
  SWIG_Python_addvarlink(p, name, get_attr, set_attr)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Python_ConvertPacked(obj, ptr, sz, ty, flags)
#define SWIG_NewPackedObj(ptr, sz, type) \
  SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_InstallConstants(d, constants) \
  SWIG_Python_InstallConstants(d, constants)

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(int)               SWIG_Python_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPointerObj(void *, swig_type_info *,int own);
SWIGIMPORT(void *)            SWIG_Python_MustGetPtr(PyObject *, swig_type_info *, int, int);
SWIGIMPORT(PyObject *)        SWIG_Python_newvarlink(void);
SWIGIMPORT(void)              SWIG_Python_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGIMPORT(int)               SWIG_Python_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGIMPORT(PyObject *)        SWIG_Python_NewPackedObj(void *, int sz, swig_type_info *);
SWIGIMPORT(void)              SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",              /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_Python_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_Python_addvarlink(PyObject *p, char *name, PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
    PyObject *zero = PyInt_FromLong(0);
    PyObject_SetAttrString(pyobj,(char*)"thisown",zero);
    Py_DECREF(zero);
  }
  return 0;

type_error:
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a pointer value, signal an exception on a type mismatch */
SWIGRUNTIME(void *)
SWIG_Python_MustGetPtr(PyObject *obj, swig_type_info *ty, int argnum, int flags) {
  void *result;
  SWIG_Python_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_Python_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c = 0;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty && c) {
      char *temp = (char *) malloc(64+strlen(ty->name)+strlen(c));
      sprintf(temp,"Type error. Got %s, expected %s", c, ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_Python_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
        PyObject *n = PyInt_FromLong(1);
        PyObject_SetAttrString(inst,(char*)"thisown",n);
        Py_DECREF(n);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_Python_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_Python_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { PyErr_SetString(PyExc_RuntimeError, (char *) msg ); goto fail; } else

#ifdef __cplusplus
}
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_FILE swig_types[0] 
#define  SWIGTYPE_p_double swig_types[1] 
#define  SWIGTYPE_p_Quat swig_types[2] 
static swig_type_info *swig_types[4];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= _quaternion.so
  ------------------------------------------------*/
#define SWIG_init    init_quaternion

#define SWIG_name    "_quaternion"

#include "quaternion.h"

char *Quat___str__(Quat *self){
    static char tmp[1024];
    sprintf(tmp,"Quat(%g,%g,%g,%g)", self->x,self->y,self->z,self->w);
    return tmp;
  }
char *Quat___repr__(Quat *self){
    static char tmp[1024];
    sprintf(tmp,"Quat(%g,%g,%g,%g)", self->x,self->y,self->z,self->w);
    return tmp;
  }
Quat *new_Quat(double x,double y,double z,double w){
    return quat_create(NULL,x,y,z,w);;
  }

static PyObject* t_output_helper(PyObject* target, PyObject* o) {
    PyObject*   o2;
    PyObject*   o3;

    if (!target) {                   
        target = o;
    } else if (target == Py_None) {  
        Py_DECREF(Py_None);
        target = o;
    } else {                         
        if (!PyTuple_Check(target)) {
            o2 = target;
            target = PyTuple_New(1);
            PyTuple_SetItem(target, 0, o2);
        }
        o3 = PyTuple_New(1);            
        PyTuple_SetItem(o3, 0, o);      

        o2 = target;
        target = PySequence_Concat(o2, o3); 
        Py_DECREF(o2);                      
        Py_DECREF(o3);
    }
    return target;
}

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_Quat_x_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:Quat_x_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->x = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Quat_x_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Quat_x_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->x);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Quat_y_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:Quat_y_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->y = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Quat_y_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Quat_y_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->y);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Quat_z_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:Quat_z_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->z = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Quat_z_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Quat_z_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->z);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Quat_w_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double arg2 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:Quat_w_set",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if (arg1) (arg1)->w = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Quat_w_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Quat_w_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double) ((arg1)->w);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Quat___str__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Quat___str__",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)Quat___str__(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_Quat___repr__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Quat___repr__",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)Quat___repr__(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_Quat(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    Quat *result;
    
    if(!PyArg_ParseTuple(args,(char *)"dddd:new_Quat",&arg1,&arg2,&arg3,&arg4)) goto fail;
    result = (Quat *)new_Quat(arg1,arg2,arg3,arg4);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_Quat(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_Quat",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * Quat_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_Quat, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_trans_identity(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 ;
    double temp1[16] ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:trans_identity",&obj0)) goto fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj0,i);
            if (PyNumber_Check(o)) {
                temp1[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg1 = temp1;
    }
    trans_identity(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg1[i]);
            PySequence_SetItem(obj0,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_trans_copy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 ;
    double *arg2 ;
    double temp1[16] ;
    double temp2[16] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:trans_copy",&obj0,&obj1)) goto fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj0,i);
            if (PyNumber_Check(o)) {
                temp1[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg1 = temp1;
    }
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj1,i);
            if (PyNumber_Check(o)) {
                temp2[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg2 = temp2;
    }
    trans_copy(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg1[i]);
            PySequence_SetItem(obj0,i,o);
        }
    }
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg2[i]);
            PySequence_SetItem(obj1,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_trans_mult_right(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 ;
    double *arg2 ;
    double temp1[16] ;
    double temp2[16] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:trans_mult_right",&obj0,&obj1)) goto fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj0,i);
            if (PyNumber_Check(o)) {
                temp1[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg1 = temp1;
    }
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj1,i);
            if (PyNumber_Check(o)) {
                temp2[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg2 = temp2;
    }
    trans_mult_right(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg1[i]);
            PySequence_SetItem(obj0,i,o);
        }
    }
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg2[i]);
            PySequence_SetItem(obj1,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_trans_mult_left(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 ;
    double *arg2 ;
    double temp1[16] ;
    double temp2[16] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:trans_mult_left",&obj0,&obj1)) goto fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj0,i);
            if (PyNumber_Check(o)) {
                temp1[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg1 = temp1;
    }
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj1,i);
            if (PyNumber_Check(o)) {
                temp2[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg2 = temp2;
    }
    trans_mult_left(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg1[i]);
            PySequence_SetItem(obj0,i,o);
        }
    }
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg2[i]);
            PySequence_SetItem(obj1,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_trans_transpose(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 ;
    double temp1[16] ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:trans_transpose",&obj0)) goto fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj0,i);
            if (PyNumber_Check(o)) {
                temp1[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg1 = temp1;
    }
    trans_transpose(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg1[i]);
            PySequence_SetItem(obj0,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_trans_inverse(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 ;
    double *arg2 ;
    int result;
    double temp1[16] ;
    double temp2[16] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:trans_inverse",&obj0,&obj1)) goto fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj0,i);
            if (PyNumber_Check(o)) {
                temp1[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg1 = temp1;
    }
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj1,i);
            if (PyNumber_Check(o)) {
                temp2[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg2 = temp2;
    }
    result = (int)trans_inverse(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg1[i]);
            PySequence_SetItem(obj0,i,o);
        }
    }
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg2[i]);
            PySequence_SetItem(obj1,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_trans_vec_mult(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 ;
    double *arg2 ;
    double temp1[16] ;
    double temp2[4] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:trans_vec_mult",&obj0,&obj1)) goto fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj0,i);
            if (PyNumber_Check(o)) {
                temp1[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg1 = temp1;
    }
    {
        int i;
        for (i = 0; i < 4; i++) {
            PyObject *o = PySequence_GetItem(obj1,i);
            if (PyNumber_Check(o)) {
                temp2[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg2 = temp2;
    }
    trans_vec_mult(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg1[i]);
            PySequence_SetItem(obj0,i,o);
        }
    }
    {
        int i;
        for (i = 0; i < 4; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg2[i]);
            PySequence_SetItem(obj1,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_trans_dump(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    FILE *arg1 = (FILE *) 0 ;
    double *arg2 ;
    double temp2[16] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:trans_dump",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_FILE,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj1,i);
            if (PyNumber_Check(o)) {
                temp2[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg2 = temp2;
    }
    trans_dump(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg2[i]);
            PySequence_SetItem(obj1,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_trans_to_quat(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double *arg2 ;
    Quat *result;
    double temp2[16] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:trans_to_quat",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj1,i);
            if (PyNumber_Check(o)) {
                temp2[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg2 = temp2;
    }
    result = (Quat *)trans_to_quat(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg2[i]);
            PySequence_SetItem(obj1,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_to_trans(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    double *arg1 ;
    Quat *arg2 = (Quat *) 0 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    double temp1[16] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOddd:quat_to_trans",&obj0,&obj1,&arg3,&arg4,&arg5)) goto fail;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PySequence_GetItem(obj0,i);
            if (PyNumber_Check(o)) {
                temp1[i] = PyFloat_AsDouble(o);
            } else {
                PyErr_SetString(PyExc_ValueError,"Sequence elements must be numbers");      
                return NULL;
            }
        }
        arg1 = temp1;
    }
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    quat_to_trans(arg1,arg2,arg3,arg4,arg5);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        int i;
        for (i = 0; i < 16; i++) {
            PyObject *o = PyFloat_FromDouble((double) arg1[i]);
            PySequence_SetItem(obj0,i,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_copy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    Quat *arg2 = (Quat *) 0 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:quat_copy",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_copy(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_nrm_sqrt(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    Quat *arg2 = (Quat *) 0 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:quat_nrm_sqrt",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_nrm_sqrt(arg1,(Quat const *)arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_normalize(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:quat_normalize",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_normalize(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_mult_right(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    Quat *arg2 = (Quat *) 0 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:quat_mult_right",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_mult_right(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_mult_left(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    Quat *arg2 = (Quat *) 0 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:quat_mult_left",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_mult_left(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_identity(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:quat_identity",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_identity(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_conjugate(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:quat_conjugate",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_conjugate(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_create(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    int arg5 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Odddi:quat_create",&obj0,&arg2,&arg3,&arg4,&arg5)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_create(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_from_axis_angle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Odddd:quat_from_axis_angle",&obj0,&arg2,&arg3,&arg4,&arg5)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_from_axis_angle(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_to_axis_angle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double *arg2 = (double *) 0 ;
    double *arg3 = (double *) 0 ;
    double *arg4 = (double *) 0 ;
    double *arg5 = (double *) 0 ;
    double temp2 ;
    double temp3 ;
    double temp4 ;
    double temp5 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOOO:quat_to_axis_angle",&obj0,&obj1,&obj2,&obj3,&obj4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        temp2 = PyFloat_AsDouble(obj1);
        if (PyErr_Occurred()) SWIG_fail;
        arg2 = &temp2;
    }
    {
        temp3 = PyFloat_AsDouble(obj2);
        if (PyErr_Occurred()) SWIG_fail;
        arg3 = &temp3;
    }
    {
        temp4 = PyFloat_AsDouble(obj3);
        if (PyErr_Occurred()) SWIG_fail;
        arg4 = &temp4;
    }
    {
        temp5 = PyFloat_AsDouble(obj4);
        if (PyErr_Occurred()) SWIG_fail;
        arg5 = &temp5;
    }
    quat_to_axis_angle(arg1,arg2,arg3,arg4,arg5);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg2));
        resultobj = t_output_helper(resultobj,o);
    }
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg3));
        resultobj = t_output_helper(resultobj,o);
    }
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg4));
        resultobj = t_output_helper(resultobj,o);
    }
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg5));
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_from_euler_RzRyRx(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    Quat *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oddd:quat_from_euler_RzRyRx",&obj0,&arg2,&arg3,&arg4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (Quat *)quat_from_euler_RzRyRx(arg1,arg2,arg3,arg4);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Quat, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_quat_to_euler_RzRyRx(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Quat *arg1 = (Quat *) 0 ;
    double *arg2 = (double *) 0 ;
    double *arg3 = (double *) 0 ;
    double *arg4 = (double *) 0 ;
    int result;
    double temp2 ;
    double temp3 ;
    double temp4 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOO:quat_to_euler_RzRyRx",&obj0,&obj1,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Quat,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        temp2 = PyFloat_AsDouble(obj1);
        if (PyErr_Occurred()) SWIG_fail;
        arg2 = &temp2;
    }
    {
        temp3 = PyFloat_AsDouble(obj2);
        if (PyErr_Occurred()) SWIG_fail;
        arg3 = &temp3;
    }
    {
        temp4 = PyFloat_AsDouble(obj3);
        if (PyErr_Occurred()) SWIG_fail;
        arg4 = &temp4;
    }
    result = (int)quat_to_euler_RzRyRx(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg2));
        resultobj = t_output_helper(resultobj,o);
    }
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg3));
        resultobj = t_output_helper(resultobj,o);
    }
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg4));
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"Quat_x_set", _wrap_Quat_x_set, METH_VARARGS },
	 { (char *)"Quat_x_get", _wrap_Quat_x_get, METH_VARARGS },
	 { (char *)"Quat_y_set", _wrap_Quat_y_set, METH_VARARGS },
	 { (char *)"Quat_y_get", _wrap_Quat_y_get, METH_VARARGS },
	 { (char *)"Quat_z_set", _wrap_Quat_z_set, METH_VARARGS },
	 { (char *)"Quat_z_get", _wrap_Quat_z_get, METH_VARARGS },
	 { (char *)"Quat_w_set", _wrap_Quat_w_set, METH_VARARGS },
	 { (char *)"Quat_w_get", _wrap_Quat_w_get, METH_VARARGS },
	 { (char *)"Quat___str__", _wrap_Quat___str__, METH_VARARGS },
	 { (char *)"Quat___repr__", _wrap_Quat___repr__, METH_VARARGS },
	 { (char *)"new_Quat", _wrap_new_Quat, METH_VARARGS },
	 { (char *)"delete_Quat", _wrap_delete_Quat, METH_VARARGS },
	 { (char *)"Quat_swigregister", Quat_swigregister, METH_VARARGS },
	 { (char *)"trans_identity", _wrap_trans_identity, METH_VARARGS },
	 { (char *)"trans_copy", _wrap_trans_copy, METH_VARARGS },
	 { (char *)"trans_mult_right", _wrap_trans_mult_right, METH_VARARGS },
	 { (char *)"trans_mult_left", _wrap_trans_mult_left, METH_VARARGS },
	 { (char *)"trans_transpose", _wrap_trans_transpose, METH_VARARGS },
	 { (char *)"trans_inverse", _wrap_trans_inverse, METH_VARARGS },
	 { (char *)"trans_vec_mult", _wrap_trans_vec_mult, METH_VARARGS },
	 { (char *)"trans_dump", _wrap_trans_dump, METH_VARARGS },
	 { (char *)"trans_to_quat", _wrap_trans_to_quat, METH_VARARGS },
	 { (char *)"quat_to_trans", _wrap_quat_to_trans, METH_VARARGS },
	 { (char *)"quat_copy", _wrap_quat_copy, METH_VARARGS },
	 { (char *)"quat_nrm_sqrt", _wrap_quat_nrm_sqrt, METH_VARARGS },
	 { (char *)"quat_normalize", _wrap_quat_normalize, METH_VARARGS },
	 { (char *)"quat_mult_right", _wrap_quat_mult_right, METH_VARARGS },
	 { (char *)"quat_mult_left", _wrap_quat_mult_left, METH_VARARGS },
	 { (char *)"quat_identity", _wrap_quat_identity, METH_VARARGS },
	 { (char *)"quat_conjugate", _wrap_quat_conjugate, METH_VARARGS },
	 { (char *)"quat_create", _wrap_quat_create, METH_VARARGS },
	 { (char *)"quat_from_axis_angle", _wrap_quat_from_axis_angle, METH_VARARGS },
	 { (char *)"quat_to_axis_angle", _wrap_quat_to_axis_angle, METH_VARARGS },
	 { (char *)"quat_from_euler_RzRyRx", _wrap_quat_from_euler_RzRyRx, METH_VARARGS },
	 { (char *)"quat_to_euler_RzRyRx", _wrap_quat_to_euler_RzRyRx, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_FILE[] = {{"_p_FILE", 0, "FILE *", 0},{"_p_FILE"},{0}};
static swig_type_info _swigt__p_double[] = {{"_p_double", 0, "Transform", 0},{"_p_double"},{0}};
static swig_type_info _swigt__p_Quat[] = {{"_p_Quat", 0, "Quat *", 0},{"_p_Quat"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_FILE, 
_swigt__p_double, 
_swigt__p_Quat, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

