/****************
 * This table contains DICOM TransferSyntax data.
 * It is automatically generated by the program 
 * generateDicomTransferSyntaxTable.java
 * using the TransferSyntax class com.pixelmed.dicom.TransferSyntax
 * (http://www.pixelmed.com/index.html#PixelMedJavaDICOMToolkit).  See
 * that web page for copyright information.  
 *
 * NOTE that spaces have been manually removed from the name values, 
 * and entry point names have been added.
 *
 * -Joel Welling, Carnegie Mellon University, 10/20/04.
 *
 ***************************
 * The data elements listed in this table are defined with the following
 * format:
 *
 *    { name, UID, isLittleEndian, isExplicitVR, isEncapsulated,
 *       isBZip2ed, isDeflated }
 *
 ****************/

#ifndef INCL_DICOM_TRANSFER_SYNTAX_H
#define INCL_DICOM_TRANSFER_SYNTAX_H

static TransferSyntax transferSyntaxTable[]= {
  {"DeflatedExplicitVRLittleEndian", "1.2.840.10008.1.2.1.99", 1, 1, 0, 0, 1},
  {"ExplicitVRBigEndian", "1.2.840.10008.1.2.2", 0, 1, 0, 0, 0},
  {"ExplicitVRLittleEndian", "1.2.840.10008.1.2.1", 1, 1, 0, 0, 0},
  {"ImplicitVRLittleEndian", "1.2.840.10008.1.2", 1, 0, 0, 0, 0},
  {"JPEG2000", "1.2.840.10008.1.2.4.91", 1, 1, 1, 0, 0},
  {"JPEG2000LosslessOnly", "1.2.840.10008.1.2.4.90", 1, 1, 1, 0, 0},
  {"JPEGBaseline", "1.2.840.10008.1.2.4.50", 1, 1, 1, 0, 0},
  {"JPEGExtended", "1.2.840.10008.1.2.4.51", 1, 1, 1, 0, 0},
  {"JPEGLossless", "1.2.840.10008.1.2.4.57", 1, 1, 1, 0, 0},
  {"JPEGLossless SV1", "1.2.840.10008.1.2.4.70", 1, 1, 1, 0, 0},
  {"JPEG-LS", "1.2.840.10008.1.2.4.80", 1, 1, 1, 0, 0},
  {"JPEG-LSNear-lossless", "1.2.840.10008.1.2.4.81", 1, 1, 1, 0, 0},
  {"MPEG2MPML", "1.2.840.10008.1.2.4.100", 1, 1, 1, 0, 0},
  {"PixelMedBzip2ExplicitVRLittleEndian", "1.3.6.1.4.1.5962.300.1", 1, 1, 0, 1, 0},
  {"PixelMedEncapsulatedRawLittleEndian", "1.3.6.1.4.1.5962.300.2", 1, 1, 1, 0, 0},
};

#endif /* INCL_DICOM_TRANSFER_SYNTAX_H */
