/* These values are extracted by hand from a Matlab routine provided by
 * Lawrence L. Wald (wald@nmr.mgh.harvard.edu).
 */


#ifndef SMNSKSPC_HDRS_DEFINED
#define SMNSKSPC_HDRS_DEFINED 1

#define SMNSKSPC_HEADER_SIZE_BYTES 32
#define SMNSKSPC_HEADER_OFF 0
#define SMNSKSPC_LINE_HDR_BYTES 128
#define SMNSKSPC_NUM_FREE_PARAMS 8

#define SMNSKSPC_DMALENGTH_OFF                    0
#define SMNSKSPC_MEASUID_OFF                      4
#define SMNSKSPC_SCANCOUNTER_OFF                  8
#define SMNSKSPC_TIMESTAMP_OFF                   12
#define SMNSKSPC_PMUTIMESTAMP_OFF                16
#define SMNSKSPC_EVALINFOMASK_OFF                20

#define SMNSKSPC_SAMPLESINSCAN_OFF               28
#define SMNSKSPC_USEDCHANNELS_OFF                30
#define SMNSKSPC_LINENUM_OFF                     32
#define SMNSKSPC_ACQNUM_OFF                      34
#define SMNSKSPC_SLICENUM_OFF                    36
#define SMNSKSPC_PARTITIONNUM_OFF                38
#define SMNSKSPC_ECHONUM_OFF                     40
#define SMNSKSPC_PHASENUM_OFF                    42
#define SMNSKSPC_REPNUM_OFF                      44
#define SMNSKSPC_SETNUM_OFF                      46
#define SMNSKSPC_SEGNUM_OFF                      48
#define SMNSKSPC_FREENUM_OFF                     50
#define SMNSKSPC_CUTOFF_PRE_OFF                  52
#define SMNSKSPC_CUTOFF_POST_OFF                 54

#define SMNSKSPC_KSPACECTRCOL_OFF                64
#define SMNSKSPC_KSPACECTRLINE_OFF               76
#define SMNSKSPC_KSPACECTRPARTITION_OFF          78

#define SMNSKSPC_READOUTOFFCTR_OFF               70
#define SMNSKSPC_TIMESINCELASTRF_OFF             74

#define SMNSKSPC_FREEPARAMS_OFF                  80 /*NUM_FREE_PARAMS ushorts*/

#define SMNSKSPC_SLICEPOS_SAG_OFF                96
#define SMNSKSPC_SLICEPOS_COR_OFF               100
#define SMNSKSPC_SLICEPOS_TRA_OFF               104

#define SMNSKSPC_QUATERNION_OFF                 108

#define SMNSKSPC_CHANNELID_OFF                  124


#define SMNSKSPC_EVALINFOMASK_ACQEND_BIT               0
#define SMNSKSPC_EVALINFOMASK_RTFEEDBACK_BIT           1
#define SMNSKSPC_EVALINFOMASK_HPFEEDBACK_BIT           2
#define SMNSKSPC_EVALINFOMASK_ONLINE_BIT               3
#define SMNSKSPC_EVALINFOMASK_OFFLINE_BIT              4
#define SMNSKSPC_EVALINFOMASK_UNKNOWN0_BIT             5
#define SMNSKSPC_EVALINFOMASK_UNKNOWN1_BIT             6
#define SMNSKSPC_EVALINFOMASK_UNKNOWN2_BIT             7
#define SMNSKSPC_EVALINFOMASK_UNKNOWN3_BIT             8
#define SMNSKSPC_EVALINFOMASK_UNKNOWN4_BIT             9
#define SMNSKSPC_EVALINFOMASK_UNKNOWN5_BIT            10
#define SMNSKSPC_EVALINFOMASK_UNKNOWN6_BIT            11
#define SMNSKSPC_EVALINFOMASK_UNKNOWN7_BIT            12
#define SMNSKSPC_EVALINFOMASK_UNKNOWN8_BIT            13
#define SMNSKSPC_EVALINFOMASK_REFPHASESTABSCAN_BIT    14
#define SMNSKSPC_EVALINFOMASK_PHASESTABSCAN_BIT       15
#define SMNSKSPC_EVALINFOMASK_D3FFT_BIT               16
#define SMNSKSPC_EVALINFOMASK_SIGNREV_BIT             17
#define SMNSKSPC_EVALINFOMASK_PHASEFFT_BIT            18
#define SMNSKSPC_EVALINFOMASK_SWAPPED_BIT             19
#define SMNSKSPC_EVALINFOMASK_POSTSHAREDLINE_BIT      20
#define SMNSKSPC_EVALINFOMASK_PHASECOR_BIT            21
#define SMNSKSPC_EVALINFOMASK_ZEROLINE_BIT            22
#define SMNSKSPC_EVALINFOMASK_ZEROPARTITION_BIT       23
#define SMNSKSPC_EVALINFOMASK_REFLECT_BIT             24
#define SMNSKSPC_EVALINFOMASK_NOISEADJSCAN_BIT        25
#define SMNSKSPC_EVALINFOMASK_SHARENOW_BIT            26
#define SMNSKSPC_EVALINFOMASK_LASTMEASUREDLINE_BIT    27
#define SMNSKSPC_EVALINFOMASK_FIRSTSCANINSLICE_BIT    28
#define SMNSKSPC_EVALINFOMASK_LASTSCANINSLICE_BIT     29
#define SMNSKSPC_EVALINFOMASK_TREFFECTIVEBEGIN_BIT    30
#define SMNSKSPC_EVALINFOMASK_TREFFECTIVEEND_BIT      31

#define SMNSKSPC_EVALINFO_ACQEND_MASK (1<<SMNSKSPC_EVALINFOMASK_ACQEND_BIT)
#define SMNSKSPC_EVALINFO_RTFEEDBACK_MASK (1<<SMNSKSPC_EVALINFOMASK_RTFEEDBACK_BIT)
#define SMNSKSPC_EVALINFO_HPFEEDBACK_MASK (1<<SMNSKSPC_EVALINFOMASK_HPFEEDBACK_BIT)
#define SMNSKSPC_EVALINFO_ONLINE_MASK (1<<SMNSKSPC_EVALINFOMASK_ONLINE_BIT)
#define SMNSKSPC_EVALINFO_OFFLINE_MASK (1<<SMNSKSPC_EVALINFOMASK_OFFLINE_BIT)
#define SMNSKSPC_EVALINFO_UNKNOWN0_MASK (1<<SMNSKSPC_EVALINFOMASK_UNKNOWN0_BIT)
#define SMNSKSPC_EVALINFO_UNKNOWN1_MASK (1<<SMNSKSPC_EVALINFOMASK_UNKNOWN1_BIT)
#define SMNSKSPC_EVALINFO_UNKNOWN2_MASK (1<<SMNSKSPC_EVALINFOMASK_UNKNOWN2_BIT)
#define SMNSKSPC_EVALINFO_UNKNOWN3_MASK (1<<SMNSKSPC_EVALINFOMASK_UNKNOWN3_BIT)
#define SMNSKSPC_EVALINFO_UNKNOWN4_MASK (1<<SMNSKSPC_EVALINFOMASK_UNKNOWN4_BIT)
#define SMNSKSPC_EVALINFO_UNKNOWN5_MASK (1<<SMNSKSPC_EVALINFOMASK_UNKNOWN5_BIT)
#define SMNSKSPC_EVALINFO_UNKNOWN6_MASK (1<<SMNSKSPC_EVALINFOMASK_UNKNOWN6_BIT)
#define SMNSKSPC_EVALINFO_UNKNOWN7_MASK (1<<SMNSKSPC_EVALINFOMASK_UNKNOWN7_BIT)
#define SMNSKSPC_EVALINFO_UNKNOWN8_MASK (1<<SMNSKSPC_EVALINFOMASK_UNKNOWN8_BIT)
#define SMNSKSPC_EVALINFO_REFPHASESTABSCAN_MASK (1<<SMNSKSPC_EVALINFOMASK_REFPHASESTABSCAN_BIT)
#define SMNSKSPC_EVALINFO_PHASESTABSCAN_MASK (1<<SMNSKSPC_EVALINFOMASK_PHASESTABSCAN_BIT)
#define SMNSKSPC_EVALINFO_D3FFT_MASK (1<<SMNSKSPC_EVALINFOMASK_D3FFT_BIT)
#define SMNSKSPC_EVALINFO_SIGNREV_MASK (1<<SMNSKSPC_EVALINFOMASK_SIGNREV_BIT)
#define SMNSKSPC_EVALINFO_PHASEFFT_MASK (1<<SMNSKSPC_EVALINFOMASK_PHASEFFT_BIT)
#define SMNSKSPC_EVALINFO_SWAPPED_MASK (1<<SMNSKSPC_EVALINFOMASK_SWAPPED_BIT)
#define SMNSKSPC_EVALINFO_POSTSHAREDLINE_MASK (1<<SMNSKSPC_EVALINFOMASK_POSTSHAREDLINE_BIT)
#define SMNSKSPC_EVALINFO_PHASECOR_MASK (1<<SMNSKSPC_EVALINFOMASK_PHASECOR_BIT)
#define SMNSKSPC_EVALINFO_ZEROLINE_MASK (1<<SMNSKSPC_EVALINFOMASK_ZEROLINE_BIT)
#define SMNSKSPC_EVALINFO_ZEROPARTITION_MASK (1<<SMNSKSPC_EVALINFOMASK_ZEROPARTITION_BIT)
#define SMNSKSPC_EVALINFO_REFLECT_MASK (1<<SMNSKSPC_EVALINFOMASK_REFLECT_BIT)
#define SMNSKSPC_EVALINFO_NOISEADJSCAN_MASK (1<<SMNSKSPC_EVALINFOMASK_NOISEADJSCAN_BIT)
#define SMNSKSPC_EVALINFO_SHARENOW_MASK (1<<SMNSKSPC_EVALINFOMASK_SHARENOW_BIT)
#define SMNSKSPC_EVALINFO_LASTMEASUREDLINE_MASK (1<<SMNSKSPC_EVALINFOMASK_LASTMEASUREDLINE_BIT)
#define SMNSKSPC_EVALINFO_FIRSTSCANINSLICE_MASK (1<<SMNSKSPC_EVALINFOMASK_FIRSTSCANINSLICE_BIT)
#define SMNSKSPC_EVALINFO_LASTSCANINSLICE_MASK (1<<SMNSKSPC_EVALINFOMASK_LASTSCANINSLICE_BIT)
#define SMNSKSPC_EVALINFO_TREFFECTIVEBEGIN_MASK (1<<SMNSKSPC_EVALINFOMASK_TREFFECTIVEBEGIN_BIT)
#define SMNSKSPC_EVALINFO_TREFFECTIVEEND_MASK (1<<SMNSKSPC_EVALINFOMASK_TREFFECTIVEEND_BIT)

#define SMNSKSPC_EVALINFO(foo,mask) \
   (( SMNSKSPC_EVALINFO_##foo##_MASK & mask )!=0)

#endif
