#ifndef WINDAQ_HDRS_DEFINED
#define WINDAQ_HDRS_DEFINED 1
#define WINDAQ_HEADER_SIZE_BYTES 1156
#define WINDAQ_HEADER_OFF 0
#define WINDAQ_CHANNELS_OFF 0
#define WINDAQ_DATAACQ_OFF 1156
#define WINDAQ_DATAACQ_SIZE_OFF 8
#define WINDAQ_LOGO_OFF1 1154
#define WINDAQ_LOGO_OFF2 1155
#define WINDAQ_LOGO_SIZE 2
#endif
